version: "3"

services:
  run-test:
          #    network_mode: host
    environment:
      - DISPLAY=10.186.156.40:0
      - CHIP=o20
      - BRANCH=@webos4tv
      - BUILD_NUMBER=226
    image: docker-registry.lge.com/project/webos/webos-tv-unittest:chrom-test
    user: "run-test"
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - ${HOME}/.gitconfig:/root/.gitconfig
      - ./:/work
